apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  description: This task will clean up a workspace by deleting all files.
  workspaces:
    - name: source
  steps:
    - name: remove 
      image: alpine:3
      workingDir: $(workspaces.source.path)
      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from $(workspaces.source.path) ..."
        
        if [ -d "$(workspaces.source.path)" ] ; then
          rm -rf "$(workspaces.source.path)"/*
          rm -rf "$(workspaces.source.path)"/.[!.]*
          rm -rf "$(workspaces.source.path)"/..?*
        fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-tests
spec:
  description: This task will execute nosetests.
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to nose
      type: string
      default: "-v"
  steps:
    - name: nosetests
      image: python:3.9-slim
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/bash
        set -e
        python -m pip install --upgrade pip wheel
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "requirements.txt not found, skipping installation"
        fi
        nosetests $(params.args)
